
server.port=8080


spring.application.name=user-center

logging.level.root=INFO
logging.level.com.example.demo=DEBUG


spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=GMT+8
